// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhgfpekqbyfwlbogwmat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oZ2ZwZWtxYnlmd2xib2d3bWF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NjE1NjUsImV4cCI6MjA3NDEzNzU2NX0.pdaL6kTl2HR2xxakoGIXLJmC5M7IlG75ipK7rxcek_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});